#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "${script_dir}/.." && pwd)"

export BUTTERFLY_REPO_ROOT="${BUTTERFLY_REPO_ROOT:-$repo_root}"
export BUTTERFLY_SSD_ROOT="${BUTTERFLY_SSD_ROOT:-/Volumes/VIXinSSD}"
export BUTTERFLY_LLAMA_CPP_TAG="${BUTTERFLY_LLAMA_CPP_TAG:-b8656}"
export BUTTERFLY_ZMLX_ROOT="${BUTTERFLY_ZMLX_ROOT:-${BUTTERFLY_SSD_ROOT}/ZMLX}"
export HF_HOME="${HF_HOME:-${BUTTERFLY_SSD_ROOT}/hf_cache}"
export HF_HUB_CACHE="${HF_HUB_CACHE:-${HF_HOME}/hub}"
export BUTTERFLY_MODELS_ROOT="${BUTTERFLY_MODELS_ROOT:-${BUTTERFLY_SSD_ROOT}/models}"
export BUTTERFLY_TOOLCHAINS_ROOT="${BUTTERFLY_TOOLCHAINS_ROOT:-${BUTTERFLY_SSD_ROOT}/toolchains}"
export BUTTERFLY_LLAMA_CPP_SRC_ROOT="${BUTTERFLY_LLAMA_CPP_SRC_ROOT:-${BUTTERFLY_TOOLCHAINS_ROOT}/llama.cpp-src}"
export BUTTERFLY_LLAMA_CPP_BUILD_ROOT="${BUTTERFLY_LLAMA_CPP_BUILD_ROOT:-${BUTTERFLY_TOOLCHAINS_ROOT}/llama.cpp-build-${BUTTERFLY_LLAMA_CPP_TAG}}"
export BUTTERFLY_LLAMA_CPP_ROOT="${BUTTERFLY_LLAMA_CPP_ROOT:-${BUTTERFLY_TOOLCHAINS_ROOT}/llama.cpp-${BUTTERFLY_LLAMA_CPP_TAG}-metal}"
export BUTTERFLY_LLAMA_CPP_CURRENT_ROOT="${BUTTERFLY_LLAMA_CPP_CURRENT_ROOT:-${BUTTERFLY_TOOLCHAINS_ROOT}/llama.cpp-metal-current}"

if [[ -d "${BUTTERFLY_LLAMA_CPP_ROOT}/bin" ]]; then
  export PATH="${BUTTERFLY_LLAMA_CPP_ROOT}/bin:${PATH}"
fi

if [[ -d "${BUTTERFLY_LLAMA_CPP_ROOT}/lib" ]]; then
  export DYLD_LIBRARY_PATH="${BUTTERFLY_LLAMA_CPP_ROOT}/lib${DYLD_LIBRARY_PATH:+:${DYLD_LIBRARY_PATH}}"
fi

if [[ -d "${BUTTERFLY_ZMLX_ROOT}/src" ]]; then
  export PYTHONPATH="${BUTTERFLY_ZMLX_ROOT}/src${PYTHONPATH:+:${PYTHONPATH}}"
fi
